import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/Aurorabackground";
import Layout from "@/components/Layout";
import Cursor from "@/components/Cursor";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Cursor /> */}
        {/* <AuroraBackground> */}
        
          <Providers>
          <Layout>
          {children}
          </Layout>
          </Providers>          
        
        {/* </AuroraBackground> */}
      </body>
    </html>
  );
}
